@extends('layouts.mainBody')
@section('title','Tax Rules')
@section('content')
<div class="bg-light p-5">
        <!-- For demo purpose -->
        <div class="container py-1">
            <div class="row text-center text-dark">
                <div class="col-lg-8 mx-auto">
                    <h1 class="display-4">Income Tax Laws</h1>

                </div>
            </div>
        </div>
        <!-- End -->


        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="accordion" id="accordionExample">
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="headingOne">
                                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                              What is Income Tax?
                            </button>
                            </h2>
                            <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                                <div class="accordion-body">
                                    <p>The term “income tax” refers to a type of tax that governments impose on income generated by businesses and individuals within their jurisdiction.</p>
                                </div>
                            </div>
                        </div>
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="headingTwo">
                                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                What is Income Tax Assessment Year?
                            </button>
                            </h2>
                            <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                                <div class="accordion-body">
                                    <p>
                                    "Assessment year" means the period of twelve months commencing on the
first day of July every year; and includes any such period which is deemed,
under the provisions of this Ordinance, to be assessment year in respect of any
income for any period.
                                    </p>

                                </div>
                            </div>
                        </div>
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="headingThree">
                                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                              What incomes allowed the income tax?
                            </button>
                            </h2>
                            <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
                                <div class="accordion-body">
                                    <p>
                                    "Income" includes-
(a) any income, profits or gains, from whatever source derived,
chargeable to tax under any provision of this Ordinance under any
head specified in section 20;
(b) any loss of such income, profits or gains;
(c) the profits and gains of any business of insurance carried on by a
mutual insurance association computed in accordance with paragraph
8 of the Fourth Schedule;
(d) any sum deemed to be income, or any income accruing or arising
or received, or deemed to accrue or arise or be received in Bangladesh
under any provision of this Ordinance.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </div>
@endsection
